# ruoyi-auth 微服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-auth
  namespace: ruoyi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-auth
  template:
    metadata:
      labels:
        app: ruoyi-auth
    spec:
      containers:
        - name: ruoyi-auth
          image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/auth:ruoyi
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-auth
  namespace: ruoyi-cloud
spec:
  selector:
    app: ruoyi-auth
  ports:
    - port: 9200
      targetPort: 9200
  type: ClusterIP
