# ruoyi-job 微服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-job
  namespace: ruoyi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-job
  template:
    metadata:
      labels:
        app: ruoyi-job
    spec:
      containers:
        - name: ruoyi-job
          image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/job:ruoyi
          ports:
            - containerPort: 9203
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-job
  namespace: ruoyi-cloud
spec:
  selector:
    app: ruoyi-job
  ports:
    - port: 9203
      targetPort: 9203
  type: ClusterIP

