apiVersion: v1
kind: Service
metadata:
  name: ruoyi-redis
  namespace: ruoyi-cloud
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: ruoyi-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ruoyi-redis
  namespace: ruoyi-cloud
spec:
  serviceName: ruoyi-redis
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-redis
  template:
    metadata:
      labels:
        app: ruoyi-redis
    spec:
      containers:
      - name: redis
        image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/redis:ruoyi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-cache
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ruoyi-sc
      resources:
        requests:
          storage: 500Mi

