apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-sentinel
  namespace: ruoyi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-sentinel
  template:
    metadata:
      labels:
        app: ruoyi-sentinel
    spec:
      containers:
        - name: sentinel
          image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/sentinel:ruoyi
          ports:
            - containerPort: 8718
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-sentinel
  namespace: ruoyi-cloud
spec:
  type: NodePort
  ports:
    - port: 8718
      targetPort: 8718
      nodePort: 30070
  selector:
    app: ruoyi-sentinel

