# ruoyi-system 微服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-system
  namespace: ruoyi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-system
  template:
    metadata:
      labels:
        app: ruoyi-system
    spec:
      containers:
        - name: ruoyi-system
          image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/system:ruoyi
          ports:
            - containerPort: 9201
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-system
  namespace: ruoyi-cloud
spec:
  selector:
    app: ruoyi-system
  ports:
    - port: 9201
      targetPort: 9201
  type: ClusterIP
