# ruoyi-visual (监控) 微服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-visual
  namespace: ruoyi-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-visual
  template:
    metadata:
      labels:
        app: ruoyi-visual
    spec:
      containers:
        - name: ruoyi-visual
          image: crpi-yd1hst2e6z04e4nc.cn-hangzhou.personal.cr.aliyuncs.com/cloudruoyi/visual:ruoyi
          ports:
            - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-visual
  namespace: ruoyi-cloud
spec:
  selector:
    app: ruoyi-visual
  ports:
    - port: 9100
      targetPort: 9100
  type: ClusterIP
